services:
  postgres:
    image: postgres:16
    container_name: media-postgres
    environment:
      POSTGRES_DB: media_cms
      POSTGRES_USER: media_user
      POSTGRES_PASSWORD: media_pass
    ports:
      - "15432:5432"



  mongo:
    image: mongo:7
    container_name: media-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
